### ISSUE TITLE
`x/2 + x` does not evaluate into `3/2 x`

### ISSUE THREAD

**Issue by grondilu** [grzegorzmazur/yacas#240]
`.5*x + x` evaluates into `1.5*x`, but `x/2 + x` does not evaluate to `3/2*x`.   Not sure it's normal.

I'm using yacas version 1.3.6

**Comment by grzegorzmazur** [comment]
You're right, it's definitely not the optimal behaviour. The workaround is to run Simplify(), in this case it works as expected, returning (3*x)/2. I'll have a look if this transformation can be made automatically without breaking anything else.

BTW, 1.3.6 is quite old. Is there a reason you stick with so ancient version? I'm asking because if there's something wrong with the recent release, I'd like to know to have a chance to fix it.

Thanks for the report
