### ISSUE TITLE
Wrong short-hand

### ISSUE THREAD

**Issue by mikldk** [grzegorzmazur/yacas#275]
In `scripts/multivar.rep/code.ys` there is this line:
```
10 # MultiLM(multi_IsMulti) <-- MultiDegree(multi);
```
Should that instead be
```
10 # MultiLM(multi_IsMulti) <-- MultiLeadingMono(multi);
```
I.e. `MultiLeadingMono()` instead of `MultiDegree`?

**Comment by grzegorzmazur** [comment]
Hi,

Definitely looks suspicious. Unfortunately, fixing this requires fixing the calls as well. Which actually leads me to a conclusion that this shorthands are not so great and perhaps should be just removed. What do you think?

Cheers,
Grzesiek

**Comment by mikldk** [comment]
I don't have a strong opinion. But in principle I prefer clear naming without aliases. I don't know enough about algebra to know which of the namings are the most common. But the longer are less esoteric.

**Comment by grzegorzmazur** [comment]
Not being an expert either, I've noticed that for obvious reasons typical mathematical notation is more on the concise side - that's a clear win when you have to write a lot of it. On the other hand eg. Mathematica naming convention is quite verbose, they in principle do not use abbreviations at all except for a few very common names like trigonometric functions. And I admit that I like it, it's quite easy to guess how to write what you want, contrary to Maple (but I've used Maple only for a short time long time ago so I may be wrong here). That's why I'd rather have verbose names and get rid of the abbreviated ones.

OK, because it seems that we agree on this, I'll remove the abbreviated names once I'm done with solving polynomial systems (should be soon).
